### PR TITLE
i-bem: 30% speed improvement by better escaping

### PR DESCRIPTION
**Pull request by indutny**
- faster escaping of xml/attributes
- less time in creating context
- avoid hidden class creation by using $$registerExtensions

Please merge and release! ;)

### CODE REVIEW

**Comment by tadatuta** [comment]
cc @arikon

**Comment by arikon** [comment]
@indutny Where to read about `$$registerExtensions()`?

**Comment by arikon** [comment]
@indutny BTW, :+1:

**Comment by mishanga** [comment]
Неужели эскейпинг и правда дает заметный прирост? Надо прикрутить в BH.

**Comment by indutny** [comment]
@mishanga стрельбы покажут :)

@arikon this is a new xjst thing :) Basically it adds all properties that are used in `local()`/`apply()` statements to the context, thus avoiding hidden class creation.

**Comment by tadatuta** [comment]
all tests in islcomponents passed

**Comment by mishanga** [comment]
@andrewblond we need this update in enb-xjst: https://github.com/enb-bem/enb-xjst/blob/master/package.json#L30

**Comment by arikon** [comment]
@mishanga It has errors, we are trying to investigate

**Comment by indutny** [comment]
@arikon have you tried 2.1.1? 2.1.0 might be broken on some templates, indeed.

**Pull request merged**
